### ISSUE TITLE
Z-index of collapsed pages menu puts it behind the sidebar

### ISSUE THREAD

**Issue by othernotherone** [GeopJr/SveltePress#309]
![image](https://user-images.githubusercontent.com/80796696/147769452-7081bf87-4801-4479-9956-8b0fdac3661b.png)

I've added a few more page types and the UI conveniently collapses the nav into a dropdown so it's not a long string of links, but when it does, the z-index is off and it appears behind the side nav. At least in mac chrome.

I'm able to fix by adding `z-index: 8;` to the `.bx--side-nav` selector in patches.scss like so:

![image](https://user-images.githubusercontent.com/80796696/147769628-ff3571d0-9048-4bf1-982f-d7345727b5b7.png)

![image](https://user-images.githubusercontent.com/80796696/147769544-b7388408-90a2-4f95-a68f-c00ed844db2c.png)

I'm happy to make the change and submit a PR, but not quite sure where that should go ideally.

**Comment by GeopJr** [comment]
Thanks for raising this issue!

That doesn't look right, thanks for taking a look into it!

My only suggestion would be to change it to `50` instead of `8` (so there's a logical scale of `(min) -50 -> 50 (max)`:
```scss
.bx--side-nav {
	z-index: 50;
}
```

Just add at the bottom of [`./src/lib/SveltePress/theme/styles/patches.scss`](https://github.com/GeopJr/SveltePress/blob/main/src/lib/SveltePress/theme/styles/patches.scss).

Feel free to open the PR whenever you are ready & happy new year!
