### ISSUE TITLE
Font rendering issue

### ISSUE THREAD

**Issue by PlkMarudny** [GeopJr/SveltePress#75]
In comparison to the [carbodesignsystem](carbondesignsystem.com) website fonts in SveltePress are rendered in a different way:

![image](https://user-images.githubusercontent.com/4361591/131250603-f0a40261-6128-4ef4-8db0-2fbe447ef163.png)

Looks like no antialiasing is applied.

**Comment by PlkMarudny** [comment]
Actually (https://carbon-svelte.vercel.app/) also renders fonts without antialiasing applied, I guess I should look over there than.

![image](https://user-images.githubusercontent.com/4361591/131250731-7da5b1d4-8c94-4509-9475-fcb154fe6aec.png)

**Comment by GeopJr** [comment]
Thanks for raising this issue!

Looks like https://carbondesignsystem.com/ uses `IBM Plex Sans VF` while both SveltePress and https://carbon-svelte.vercel.app/ use `IBM Plex Sans`.

I'm having a bit of trouble distinguishing whether or not changing from non-VF to VF fixes the antialiasing problem and would appreciate any comment on it!

I'll attach screenshots of non-VF and VF:
non-VF
![SveltePress introduction page with the non-VF version of the fonts](https://user-images.githubusercontent.com/18014039/131251104-4da2988c-14ae-4d6f-a353-9d7712d53d62.png)
VF
![SveltePress introduction page with the VF version of the fonts](https://user-images.githubusercontent.com/18014039/131251100-0c6c3294-1194-4dc5-b530-824f07c123cb.png)

You can also give it a try yourself by applying the following change in your browser's dev tools:
![Screenshot of devtools with a change to the fonts applied](https://user-images.githubusercontent.com/18014039/131251181-e513b48c-b81a-4fea-8266-9e0e713ab6b6.png)

**Comment by PlkMarudny** [comment]
On the screenshot attached the 'VF' version actually uses 'Helvetica' (guess the 'VF' version of the font was not found). I can check the rendering, but what is a preferred way to override font-face definitions in SveltePress?

**Comment by GeopJr** [comment]
Oops, you are right 😅

Placing the following snippet in `src/routes/__layout.svelte` should be (hopefully) enough:

```svelte
<style>
	@font-face {
		font-family: 'IBM Plex Sans VF';
		src: url('https://gatsby-theme-carbon.vercel.app/fonts/IBMPlexSansLatin-VF.woff2')
			format('woff2');
	}

	:global(body) {
		font-family: 'IBM Plex Sans VF' !important;
	}
</style>
```

But it can also be done in the live version by adding the following style tag in `<head>`:
```html
<style>
	@font-face {
		font-family: 'IBM Plex Sans VF';
		src: url('https://gatsby-theme-carbon.vercel.app/fonts/IBMPlexSansLatin-VF.woff2')
			format('woff2');
	}

	body {
		font-family: 'IBM Plex Sans VF' !important;
		}
</style>
```


<details><summary>Screenshot of the VF font for real this time (hopefully)</summary>

![Screenshot of the VF font for real this time](https://user-images.githubusercontent.com/18014039/131252339-913eb823-f4c4-4071-9ea9-051f234c7a01.png)

</details>

**Comment by PlkMarudny** [comment]
Indeed, 'VF' font makes a difference. It is much nicer.

**Comment by PlkMarudny** [comment]
'VF font:

![image](https://user-images.githubusercontent.com/4361591/131297289-094321b7-5ae1-4a71-92fe-4d9217905055.png)


Non VF:

![image](https://user-images.githubusercontent.com/4361591/131297344-5b4045d3-7771-416a-9dfb-7f89148b2f28.png)

Of course, "nice" look is a matter of taste, but definitely the 'VF' font is antialiased nicely, compare the lowercase 'g' for example.
Users I presented SvelteKit to rejected it because of the font, they just called it "ugly", while VF font is serviceable to them.

**Comment by PlkMarudny** [comment]
Screenshots above come from Chrome

**Comment by GeopJr** [comment]
There are some issues that prevent me from switching to VF:
- There's a vertical alignment issue (seen at https://ttqq5.csb.app/ & on the attached video)
- The font isn't available on services like Google Fonts (https://togithub.com/carbon-design-system/okrs/issues/140)
- There's no built-in support for VF (as an alternative to the above) (https://togithub.com/carbon-design-system/okrs/issues/139)
- Using the gatsby theme vercel link mentioned in previous messages is a solution but honestly a not-so great one as I don't know if it will stay the same forever (or at least as long as google fonts would)
- Shipping with fonts is also kinda out of the question since the repo will stop being 100% unlicense

Relevant issues:

- https://togithub.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5434
- https://togithub.com/IBM/plex/issues/377
- https://togithub.com/carbon-design-system/carbon/issues/3922

Switching from Carbon to original style would solve this whole issue, but IMO Carbon makes SveltePress stand out from the other options. I understand that Carbon is not everyone's cup of tea, so providing a Material (/something that follows current trends) theme is probably the best outcome.

Switching the font with another similar could also work.

https://user-images.githubusercontent.com/18014039/131339678-fc201c2c-f5db-41ae-97c3-157db4d04cd0.mp4

**Comment by PlkMarudny** [comment]
Makes sense, just the font is ugly and make the whole thing look sub-standard somehow.
